UI improvements
tabanliviu/image-checker pull request #17
Opened 2017-05-04 16:15 UTC by simonhearne

2017-05-05 08:36 UTC, tabanliviu requested changes

2017-05-05 08:36 UTC, tabanliviu commented on app/public.js
> +    performanceEntry = performance.getEntriesByName(getUrl(element))[0];
@simonhearne MAINTENANCE - use local variable instead of global use `let`

2017-05-05 08:36 UTC, tabanliviu commented on app/public.js
> +    performanceEntry = performance.getEntriesByName(element)[0];
@simonhearne MAINTENANCE - use local variable instead of global use let

2017-05-05 08:36 UTC, tabanliviu commented on app/public.js
> +      console.log(performanceEntry);
@simonhearne MAINTENANCE - remove all console logs please

2017-05-05 08:36 UTC, tabanliviu commented on app/public.js
> +    l.href=s;
@simonhearne MAINTENANCE - use URL api 
```
let url = new URL('http://test.google.com/after?bool')
return url.hostname;
```

This will exclude ports btw.

2017-05-05 08:36 UTC, tabanliviu commented on app/styles/content.css
> +  font-size:90%;
@simonhearne CONSISTENCY - use consistent style with spaces after `:`

2017-05-05 08:36 UTC, tabanliviu commented on app/styles/content.css
> +  font-size:90%;
everywhere

2017-05-05 08:36 UTC, tabanliviu commented on app/public.js
> +    let wid = image.naturalSize.width / image.width;
@simonhearne MAINTENANCE - use readable variable names `width`, `height`

2017-05-05 08:36 UTC, tabanliviu commented on app/public.js
> +    return Math.max(wid,hei);
@simonhearne CONSISTENCY - space after comma

2017-05-05 08:36 UTC, tabanliviu commented on app/public.js
> +    return Math.max(wid,hei);
everywhere

2017-05-05 08:36 UTC, tabanliviu commented on app/public.js
> +    if (n.indexOf('?')>0) {
@simonhearne INFO - are you sure you want to eliminate query strings? some sites use them to fetch different versions of the image.

2017-05-05 08:36 UTC, tabanliviu commented on app/styles/popup.css
> +button {
@simonhearne CONSISTENCY - create a class. Don't target html tags directly.

2017-05-05 08:36 UTC, tabanliviu commented on app/styles/popup.css
> +  /*width: 390px;*/
@simonhearne MAINTENANCE - remove comment

2017-05-05 08:48 UTC, tabanliviu commented on app/public.js
> +    if (percentage < 0) col = 0;
@simonhearne CONSISTENCY - always use `{` for any if statements even if it's a single line

2017-05-05 09:38 UTC, tabanliviu commented on app/popup.html
> +      <a href="https://www.nccgroup.trust/web-performance/" id="contact">Need help?</a>
@simonhearne DoD - add `target="_blank"` as it doesn't open otherwise

2017-05-09 15:14 UTC, simonhearne commented on app/public.js
> +    if (n.indexOf('?')>0) {
This is just to render the filename in the overlay, removing query strings makes the filename more readable and the href is still available for the full image URL.

2017-05-09 15:41 UTC, tabanliviu approved these changes

2017-05-09 15:44 UTC, merged