WIP: ISSUE-32 add google analytics opt out option
tabanliviu/image-checker pull request #34
Opened 2017-05-17 17:21 UTC by tabanliviu

2017-05-22 14:10 UTC, simonhearne reviewed
I've added some text to describe what the checkbox does. Do we need to include a full privacy policy?

2017-05-22 18:52 UTC, tabanliviu commented
@simonhearne if you think it helps? perhaps a link to a predefined one?

2017-05-22 19:49 UTC, tabanliviu commented on app/options.html
> +    <p>NCC Group collects information about your use of this extension, including how many times it is opened and what pages it is used on, using Google Analytics.</p>
@simonhearne MAINTENANCE - move the description paragraphs inside the options div so it's colocated with the feature it's describing

2017-06-09 10:39 UTC, Ian-Hi commented
Verified ok

2017-06-13 16:58 UTC, MalcolmSmithUK requested changes

2017-06-13 16:58 UTC, MalcolmSmithUK commented on app/analytics.js
> +  function initGa() {
@tabanliviu CONSISTENCY - Function call adds more barriers than it assists with.

2017-06-13 19:55 UTC, tabanliviu commented on app/analytics.js
> +  function initGa() {
OK

2017-06-13 20:01 UTC, tabanliviu commented
@MalcolmSmithUK ready for review

2017-06-14 11:15 UTC, MalcolmSmithUK approved these changes

2017-06-14 11:16 UTC, MalcolmSmithUK commented on app/options.html
> +    <p>NCC Group collects information about your use of this extension, including how many times it is opened and what pages it is used on, using Google Analytics.</p>
@tabanliviu This appears to still be a thing.

2017-06-14 17:19 UTC, merged