Issue 31 - update on window resize and path change
tabanliviu/image-checker pull request #36
Opened 2017-05-22 11:15 UTC by simonhearne

I ended up implementing an interval as one was required to check for path changes anyway, it also handily debounces the resize.
onHashChange doesn't always work e.g. <https://www.oliverbonas.com/> is a SPA that updates the path, not hash. Set it at 500ms which seems like a reasonable compromise.

2017-05-22 13:48 UTC, tabanliviu requested changes

2017-05-22 13:48 UTC, tabanliviu commented on app/public.js
> +    showImagesInfo(null);
@simonhearne DoD - why send null? there is no need. undefined is good enough

2017-05-22 13:48 UTC, tabanliviu commented on app/public.js
> +    interval = setInterval(function() {
@simonhearne CONSISTENCY - `setInterval(() => {})`

2017-05-22 13:48 UTC, tabanliviu commented on app/public.js
> +    interval = setInterval(function() {
@simonhearne DoD - should clear interval before creating a new one as we're always create another interval every time showImagesInfo is called

2017-05-22 13:48 UTC, tabanliviu commented on app/public.js
> +  let interval;
@simonhearne MAINTENANCE - use a more descriptive name like `refreshImagesInterval`

2017-05-22 13:52 UTC, simonhearne commented on app/public.js
> +  let interval;
Yup, done.

2017-05-22 13:52 UTC, simonhearne commented on app/public.js
> +    showImagesInfo(null);
Fixed.

2017-05-22 13:57 UTC, simonhearne commented on app/public.js
> +    interval = setInterval(function() {
It's cleared in hideImagesInfo(). Assume we never call showImagesInfo() twice without hideImagesInfo()? Then we would get duplicate overlays. Could add a check in showImagesInfo() for isImagesInforActive() then hide first... new issue for that?

2017-05-22 13:57 UTC, simonhearne reviewed
Updated branch to include the requested changes.

2017-05-22 18:50 UTC, tabanliviu commented on app/public.js
> +    interval = setInterval(function() {
the idea is to not depend on a different method for clearing the interval. this couples those 2 methods together. in the case of calling showImagesInfo twice, it should be safe, including clearing existing overlays and existing intervals.

perhaps showImagesInfo should always call hideImagesInfo at the beginning to ensure a clean slate.

2017-05-24 16:33 UTC, tabanliviu commented
@simonhearne still need to add unit tests :smile:

2017-05-24 20:06 UTC, tabanliviu commented
fixes #31

2017-05-24 20:08 UTC, tabanliviu approved these changes

2017-06-09 10:10 UTC, Ian-Hi commented
Verified ok

2017-06-13 16:45 UTC, MalcolmSmithUK requested changes

2017-06-13 16:45 UTC, MalcolmSmithUK commented on app/public.js
> +        path = window.location.pathname;
@tabanliviu DoD - This doesn't include changes in the hash (either for traditional hash or non-HTML5 SPAs).

2017-06-13 16:45 UTC, MalcolmSmithUK commented on app/public.js
> +  function setRefreshImagesWatcher() {
@tabanliviu MAINTAINABILITY - Please clear the timeout in case another event implements the same method.

2017-06-13 19:55 UTC, tabanliviu commented on app/public.js
> +  function setRefreshImagesWatcher() {
OK

2017-06-13 19:55 UTC, tabanliviu commented on app/public.js
> +        path = window.location.pathname;
OK

2017-06-13 20:01 UTC, tabanliviu commented
@MalcolmSmithUK ready for review

2017-06-14 11:12 UTC, MalcolmSmithUK approved these changes

2017-06-14 17:12 UTC, merged