ISSUE-28 add loading message
tabanliviu/image-checker pull request #37
Opened 2017-05-24 20:04 UTC by tabanliviu

fixes #28

2017-06-09 10:09 UTC, Ian-Hi commented
Verified ok

2017-06-13 16:32 UTC, MalcolmSmithUK requested changes

2017-06-13 16:32 UTC, MalcolmSmithUK commented on app/popup.html
> +      <span id="loading">Please wait while the page loads...</span>
@tabanliviu INFO - Consider using `&hellip;` here...

2017-06-13 16:32 UTC, MalcolmSmithUK commented on app/popup.js
> +      getLoading().style.display = 'none';
@tabanliviu MAINTAINABILITY - Please refactor to use 'hide' so you don't need any special knownledge of layout in your JS.

2017-06-13 20:01 UTC, tabanliviu commented
@MalcolmSmithUK ready for review

2017-06-14 11:08 UTC, MalcolmSmithUK approved these changes

2017-06-14 17:06 UTC, merged