ISSUE-33 add scroll to overlays
tabanliviu/image-checker pull request #38
Opened 2017-05-24 21:11 UTC by tabanliviu

fixes #33

2017-06-09 10:09 UTC, Ian-Hi commented
Verified ok

2017-06-13 16:27 UTC, MalcolmSmithUK requested changes

2017-06-13 16:27 UTC, MalcolmSmithUK commented on app/public.js
> +    element.style.overflow = 'auto';
@tabanliviu MAINTAINABILITY - Please move static to CSS if possible.

2017-06-13 20:01 UTC, tabanliviu commented
@MalcolmSmithUK ready for review

2017-06-13 20:01 UTC, tabanliviu commented
@MalcolmSmithUK ready for review

2017-06-14 11:07 UTC, MalcolmSmithUK approved these changes

2017-06-14 17:23 UTC, merged