ISSUE-41 - overlays are sometimes not positioned correctly
tabanliviu/image-checker pull request #42
Opened 2017-06-21 16:55 UTC by tabanliviu

update on scroll position changes
use correct calculation for top/left on overlays

2017-06-26 17:09 UTC, MalcolmSmithUK requested changes

2017-06-26 17:09 UTC, MalcolmSmithUK commented on test/public.spec.js
> +        expect(imageOverlays.length).toEqual(2);
@tabanliviu COVERAGE - It's not clear why the assertion is related to the describe block.

2017-06-26 17:09 UTC, MalcolmSmithUK commented on test/public.spec.js
> +    bigImg.style = 'display: block;width: 300px;height: 240px;';
@tabanliviu COVERAGE - This indicates a missing test case.

2017-07-09 20:47 UTC, tabanliviu commented
@MalcolmSmithUK updated with requested changes

2017-07-17 10:56 UTC, Ian-Hi commented
http://www.msn.com/en-gb/news/uknews/woman-steals-her-stolen-bike-back-from-thief-who-advertised-it-on-facebook/ar-BBEvNtA?li=BBoPRmx is vertically mis-aligned above 1262, but fine below that width

2017-07-17 11:02 UTC, MalcolmSmithUK submitted a review, later dismissed

2017-07-17 18:10 UTC, tabanliviu commented
@Ian-Hi Updated branch can you please have a look? I've also added a manual test page that replicates the issue. see `test/manual` folder

2017-07-21 09:52 UTC, MalcolmSmithUK submitted a review, later dismissed

2017-07-24 09:06 UTC, MalcolmSmithUK requested changes

2017-07-24 09:06 UTC, MalcolmSmithUK commented on app/public.js
> +    if (elem.getBoundingClientRect) {
@tabanliviu MAINTAINABILITY - No need for the guard here - plus potential for consolidating `getImagesInfoParent` and `getElementTopLeft`.

2017-07-24 09:23 UTC, MalcolmSmithUK approved these changes

2017-07-24 13:00 UTC, merged