ISSUE-25 add support for html5 video poster images
tabanliviu/image-checker pull request #43
Opened 2017-06-23 11:08 UTC by tabanliviu

fixes #25

2017-06-23 14:43 UTC, MalcolmSmithUK requested changes

2017-06-23 14:43 UTC, MalcolmSmithUK commented on app/public.js
> +    } else if (element.tagName.toLowerCase() !== 'video' && element.currentSrc) {
@tabanliviu KISS - This indicates that the previous condition isn't reliable enough, so we're pushing the decision elsewhere.  Perhaps it makes more sense to be explicit and inclusive? Are there any other situations where simply checking for presence of currentSrc may not be suitable?

```
if (element.tagName.toLowerCase() === 'video') {
  return !!element.poster;
}
else if (element.currentSrc) {
   ...
}
else {
  ...
}
```

2017-06-23 14:43 UTC, MalcolmSmithUK commented on test/public.spec.js
> +      expect(imageOverlays.length).toEqual(6);
@tabanliviu INFO - So which condition added the extra overlay... `(empty)` or `{ poster: false }`?

2017-07-09 20:47 UTC, tabanliviu commented
@MalcolmSmithUK updated with requested changes

2017-07-09 20:48 UTC, tabanliviu commented on test/public.spec.js
> +      expect(imageOverlays.length).toEqual(6);
@MalcolmSmithUK updated with requested changes

2017-07-17 11:03 UTC, MalcolmSmithUK approved these changes

2017-07-21 09:14 UTC, merged