ISSUE-45 - add device pixel ratio support
tabanliviu/image-checker pull request #46
Opened 2017-07-09 20:39 UTC by tabanliviu

fixes #45

2017-07-17 11:07 UTC, MalcolmSmithUK requested changes

2017-07-17 11:07 UTC, MalcolmSmithUK commented on app/public.js
> +    let renderArea = window.devicePixelRatio * window.devicePixelRatio * image.width * image.height;
@tabanliviu BUG - Why are you doubling the influence of device pixel ratio?

2017-07-21 16:52 UTC, tabanliviu commented on app/public.js
> +    let renderArea = window.devicePixelRatio * window.devicePixelRatio * image.width * image.height;
Because we need to apply the pixel ratio to width and height as we're calculating an area.

2017-07-24 08:56 UTC, MalcolmSmithUK approved these changes

2017-07-24 08:56 UTC, merged